[theme]
name = "bad-wolf"

[icons]
name = "awesome"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = false
speed_up = false
speed_down = false

[[block]]
block = "bluetooth"
mac = "34:88:5D:EC:7D:99"
label = "  keyboard"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {Mup}%"
format_swap = " {SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "battery"
interval = 10
format = " {percentage}% {time}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%a %m月%d日 %R"
