# plain slick bad-wolf gruvbox-light gruvbox-dark modern
# solarized-light solarized-dark
[theme]
name = "slick"

[icons]
name = "awesome"

[[block]]
block = "battery"
interval = 10
full_format = " full "
format = " {percentage}% {time}% "

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = false
speed_up = false
speed_down = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {Mup}%"
format_swap = " {SUp}%"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
