theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true

[[block]]
block = "bluetooth"
mac = "34:88:5D:EC:7D:99"
label = " bluetooth"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
